name: Deploy to Amazon ECS

on: [ pull_request ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: 582771818121.dkr.ecr.eu-west-2.amazonaws.com/crm-service-images
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to ECS.
          mvn spring-boot:build-image
          docker tag docker.io/library/crm-service:0.0.1-SNAPSHOT 582771818121.dkr.ecr.eu-west-2.amazonaws.com/crm-service-images:0.0.1-SNAPSHOT
          docker push 582771818121.dkr.ecr.eu-west-2.amazonaws.com/crm-service-images:0.0.1-SNAPSHOT
          echo "::set-output name=image::582771818121.dkr.ecr.eu-west-2.amazonaws.com/crm-service-images:0.0.1-SNAPSHOT"

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: aws-task-definition.json
          container-name: crm-service-container
          image: ${{ steps.build-image.outputs.image }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: crm-service
          cluster: crm-service-cluster-prod
          wait-for-service-stability: true
